[package]
name = "CertificateMaker"
version = "0.1.0"
edition = "2024"

[dependencies]
image = "0.24"
png = "0.17"
anyhow = "1.0"
imageproc = "0.23"
rusttype = "0.9"
csv = "1.3"
calamine = "0.22"
serde = { version = "1.0", features = ["derive"] }
rayon = "1.8"